[package]
name = "scraper-component-macros-test"
version = "--bump"
license.workspace = true
repository.workspace = true
categories.workspace = true
readme.workspace = true
edition.workspace = true

[dependencies]
scraper-component.workspace = true
tap = "1.0.1"
